import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  dictiondary: [
    'intro',
    {
      type: 'category',
      label: '개발 용어',
      items: ['terms/peer-dependency', 'terms/interpolation'],
    },
    {
      type: 'category',
      label: '문서 번역',
      items: ['translation/top-level-await'],
    },
  ],
};

export default sidebars;
